### ISSUE TITLE
Unreachable

### ISSUE THREAD

**Issue by michsk** [meanbee/magento2-environment#6]
The domain is unreachable. I have ran setup multiple times already (times out as well)

```[Progress: 608 / 869]
Module 'Magento_InventoryShippingAdminUi':

In ErrorHandler.php line 61:
                                                                                                                                                                
  Warning: PDOStatement::execute(): MySQL server has gone away in /var/www/magento/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php on line 228  
```

But the domain keeps being unreachable. 

```
$ docker-compose ps
             Name                           Command                State              Ports         
----------------------------------------------------------------------------------------------------
magento2-environment_appdata_1   /true                            Exit 0                            
magento2-environment_cli_1       /docker-entrypoint.sh bash       Exit 137                          
magento2-environment_db_1        docker-entrypoint.sh mysqld      Up         0.0.0.0:32797->3306/tcp
magento2-environment_dbdata_1    /true                            Exit 0                            
magento2-environment_fpm_1       /docker-entrypoint.sh php- ...   Exit 137                          
magento2-environment_web_1       /usr/local/bin/docker-envi ...   Exit 0                
```

Additionally, it doesnt seem to use port 80. Am i missing something?

Could the issue be that its not working because of the setup not completing fully?

**Comment by michsk** [comment]
compose file is untouched
```
web:
  image: meanbee/magento2-nginx:1.9
  ports:
    - 80
  links:
    - fpm
    - db
  volumes_from:
    - appdata
  env_file:
    - current.env
  environment:
    - VIRTUAL_HOST=meanbee-environment.docker
    - MAGENTO_RUN_MODE=developer

appdata:
  image: tianon/true
  volumes:
    - ./magento:/var/www/magento
    - ./:/src
    - ~/.composer/cache:/root/.composer/cache

fpm:
  image: meanbee/magento2-php:7.2-fpm
  links:
    - db
  volumes_from:
    - appdata
  env_file:
    - current.env
  environment:
    - PHP_MEMORY_LIMIT=2G

db:
  image: mariadb:10.0
  ports:
    - 3306
  volumes_from:
    - dbdata
  env_file:
    - current.env
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

cli:
  image: meanbee/magento2-php:7.2-cli
  links:
    - db
  volumes:
    - ./bin:/tools
    - ./test-results:/mnt/test-results
  volumes_from:
    - appdata
  env_file:
    - composer.env
    - current.env
  environment:
    - PHP_MEMORY_LIMIT=2G
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://meanbee-environment.docker/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=magento2
    - M2SETUP_ADMIN_PASSWORD=magento2
    - M2SETUP_BACKEND_FRONTNAME=admin
    - M2SETUP_VERSION=2.3
    - M2SETUP_USE_SAMPLE_DATA=true
    - MAGENTO_ROOT=/var/www/magento
```

current.env with some modifications i found online.

```
$ cat current.env
MAGENTO_RUN_MODE=developer
PHP_MEMORY_LIMIT=2048M
PHP_ENABLE_XDEBUG=false
UPDATE_UID_GID=true
DEBUG=false
ENABLE_SENDMAIL=true
UPLOAD_MAX_FILESIZE=64M
```
